version: !!str 3.7

services:
  discord:
    build: .
    container_name: discord-notifier
    environment:
      TOKEN: "your bot token"
      HOOK: "your server's webhook"
      USER_ID: "extra user id to notify"
      SENDER_HOOK_NAME: "the webhook name that is used by alertmanager"
      MESSAGE: "<@USER_ID> your custom message."