version: !!str 3.7

services:
  discord:
    build: .
    container_name: discord-notifier
    environment:
      TOKEN: "your bot token"
      HOOK: "your server's webhook"
      ADMIN_ID: "your server admin id" 
      USER_ID: "extra user id to notify"
      SENDER_ID: "Spidey Bot"

# TODO : sync env vars with the actual one used in the programm
# TODO : add custom message env var with a default value.