name: CI

on:
  push:
    branches:
      - dev
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: devopsteen/discord-notifier:latest
  
  # pr: 
  #   name: pull request
  #   runs-on: ubuntu-latest

  #   env:
  #     PR_BRANCH: release-ci-${{ github.sha }}

  #   steps:
  #     - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
  #     - name: Create Branch
  #       run: |
  #         git checkout -b ${{ env.PR_BRANCH }}

  release:
    name: Release
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    
    env:
      tag: v1.0.6
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: devopsteen/discord-notifier:${{ env.tag }}


      - name: Create Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          token: ${{ github.token }}
          tag_name: ${{ env.tag }}
          prerelease: true
          draft: false
          generate_release_notes: true
          name: ${{ env.tag }}
